"""Add leaderboards table

Revision ID: 01bb74eba2d4
Revises: 15ebc74d9eb4
Create Date: 2026-03-25 18:22:37.856853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01bb74eba2d4'
down_revision: Union[str, Sequence[str], None] = '15ebc74d9eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('fields_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_field', sa.String(), nullable=False),
    sa.Column('sort_order', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboards_slug'), 'leaderboards', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboards_slug'), table_name='leaderboards')
    op.drop_table('leaderboards')
    # ### end Alembic commands ###
