"""Add cascade delete to entries

Revision ID: 92073b6e0097
Revises: e31f354fc5ea
Create Date: 2026-05-17 09:15:25.410386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92073b6e0097'
down_revision: Union[str, Sequence[str], None] = 'e31f354fc5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entries_leaderboard_id_fkey'), 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'leaderboards', ['leaderboard_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key(op.f('entries_leaderboard_id_fkey'), 'entries', 'leaderboards', ['leaderboard_id'], ['id'])
    # ### end Alembic commands ###
